version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ServerlessSpaceKadetBackendAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gqbm9jr80t38"
s3_prefix = "ServerlessSpaceKadetBackendAPI"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
